/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NftProjectDemo } from "./NftProjectDemo";
export type { SemogaBerhasil } from "./SemogaBerhasil";
