/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Airdrop } from "./Airdrop";
export type { InterfaceAvatar } from "./InterfaceAvatar";
export type { TestRealityChainAvatar } from "./TestRealityChainAvatar";
