/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropSol from "./Airdrop.sol";
export type { airdropSol };
import type * as contractTesting from "./contract-testing";
export type { contractTesting };
export type { AvatarNFT } from "./AvatarNFT";
