/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NftProjectDemo__factory } from "./NftProjectDemo__factory";
export { SemogaBerhasil__factory } from "./SemogaBerhasil__factory";
